name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Web App & Add Android
      run: |
        npx cap add android || true
        npx cap sync android

    - name: Set up Java JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Android APK
      run: |
        # التأكد من وجود ملفات gradle وفي حال عدم وجودها يتم إنشاؤها تلقائياً
        if [ ! -f "android/gradlew" ]; then
          rm -rf android
          npx cap add android
        fi
        mkdir -p android/app
        npx cap copy android
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
